version: '3'

services:
  sous-postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/code
    ports:
      - 8080:8080
